# Generated by Django 5.2 on 2025-07-13 11:02

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Any', 'Any'), ('CSE', 'CSE'), ('ICT', 'ICT'), ('ES', 'Environmental Science'), ('ENG', 'English'), ('ECO', 'Economics'), ('IR', 'International Relations'), ('LAW', 'Law'), ('PA', 'Public Administration'), ('SOC', 'Sociology'), ('DS', 'Development Studies'), ('MCJ', 'Mass Communication & Journalism'), ('DMR', 'Disaster Management & Resilience'), ('PCHR', 'Peace, Conflict and Human Rights'), ('GEN', 'Business Administration - General'), ('AIS', 'Accounting & Information Systems'), ('MGT', 'Management Studies'), ('MKT', 'Marketing'), ('FNB', 'Finance & Banking'), ('BA/BSS', 'BA/BSS')], max_length=50)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=2)),
                ('degree', models.CharField(choices=[('BSc', 'Bachelor of Science'), ('MSc', 'Master of Science')], max_length=3)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
