# Generated by Django 5.2 on 2025-07-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='user_pic/'),
        ),
    ]
