# Generated by Django 5.2 on 2025-06-10 12:15

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='roomPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('looking_house', 'Looking for House'), ('looking_roommate', 'Looking for Roommates')], max_length=16)),
                ('rent', models.PositiveIntegerField(help_text='Enter monthly rent')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('food', models.CharField(choices=[('self', 'Self Arrange'), ('shared', 'Shared Cooking (Schedule)'), ('helper', 'Combined Paid Helper')], max_length=20)),
                ('area', models.CharField(choices=[('Uttara East', 'Uttara East (Sectors 1-9)'), ('Uttara West', 'Uttara West (Sectors 10-18)'), ('House Building', 'House Building (Uttara Hub)'), ('Azampur', 'Azampur (Uttara Link)'), ('Airport', 'Airport (Hazrat Shahjalal)'), ('Abdullahpur', 'Abdullahpur'), ('Diabari', 'Diabari'), ('Kamarpara', 'Kamarpara'), ('Khilkhet', 'Khilkhet (East of Airport)'), ('Tongi', 'Tongi'), ('Shyamoli', 'Shyamoli'), ('Agargaon', 'Agargaon'), ('Kafrul', 'Kafrul (West Agargaon)'), ('Kazipara', 'Kazipara (Near Mirpur 10)'), ('Shewrapara', 'Shewrapara (On Mirpur Road)'), ('Taltola', 'Taltola (Mirpur-Mohammadpur link)'), ('Pallabi', 'Pallabi'), ('Alubdi', 'Alubdi (Pallabi outskirts)'), ('Monipur', 'Monipur (School & Housing Area)'), ('Mirpur DOHS', 'Mirpur DOHS'), ('Mirpur 1', 'Mirpur Section 1'), ('Mirpur 2', 'Mirpur Section 2'), ('Mirpur 6', 'Mirpur Section 6'), ('Mirpur 10', 'Mirpur Section 10'), ('Mirpur 11', 'Mirpur Section 11'), ('Mirpur 12', 'Mirpur Section 12'), ('Mirpur 14', 'Mirpur Kalshi'), ('Mohammadpur', 'Mohammadpur'), ('Dhanmondi', 'Dhanmondi'), ('Farmgate', 'Farmgate')], max_length=100)),
                ('department', models.CharField(choices=[('ANY', 'Any'), ('CSE', 'CSE'), ('ICT', 'ICT'), ('ES', 'Environmental Science'), ('ENG', 'English'), ('ECO', 'Economics'), ('IR', 'International Relations'), ('LAW', 'Law'), ('PA', 'Public Administration'), ('SOC', 'Sociology'), ('DS', 'Development Studies'), ('MCJ', 'Mass Communication & Journalism'), ('DMR', 'Disaster Management & Resilience'), ('PCHR', 'Peace, Conflict and Human Rights'), ('GEN', 'Business Administration - General'), ('AIS', 'Accounting & Information Systems'), ('MGT', 'Management Studies'), ('MKT', 'Marketing'), ('FNB', 'Finance & Banking'), ('BA/BSS', 'BA/BSS'), ('Any', 'Any')], max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('room_type', models.CharField(choices=[('private', 'Private Room'), ('shared', 'Shared Room'), ('Any', 'Any')], max_length=10)),
                ('full_address', models.TextField(blank=True, help_text='Write Address in detail', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('dist_from_bup', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
