# Generated by Django 5.2 on 2025-06-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate_finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roompost',
            name='department',
            field=models.CharField(choices=[('Any', 'Any'), ('CSE', 'CSE'), ('ICT', 'ICT'), ('ES', 'Environmental Science'), ('ENG', 'English'), ('ECO', 'Economics'), ('IR', 'International Relations'), ('LAW', 'Law'), ('PA', 'Public Administration'), ('SOC', 'Sociology'), ('DS', 'Development Studies'), ('MCJ', 'Mass Communication & Journalism'), ('DMR', 'Disaster Management & Resilience'), ('PCHR', 'Peace, Conflict and Human Rights'), ('GEN', 'Business Administration - General'), ('AIS', 'Accounting & Information Systems'), ('MGT', 'Management Studies'), ('MKT', 'Marketing'), ('FNB', 'Finance & Banking'), ('BA/BSS', 'BA/BSS'), ('Any', 'Any')], max_length=50),
        ),
        migrations.AlterField(
            model_name='roompost',
            name='food',
            field=models.CharField(choices=[('self', 'Self Arrange'), ('shared', 'Shared Cooking (Schedule)'), ('helper', 'Combined Paid Helper'), ('Any', 'Any')], max_length=20),
        ),
    ]
