# Generated by Django 5.2 on 2025-06-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate_finder', '0005_alter_roompost_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roompost',
            name='area',
            field=models.CharField(choices=[('Uttara East', 'Uttara East'), ('Uttara General Hospital', 'Uttara West'), ('Uttara Center, Tafalia Main Road, Uludaha, Baunia, Dhaka, Dhaka Metropolitan,1231', 'Uttara Center'), ('House Building', 'House Building (Uttara Hub)'), ('Azampur', 'Azampur (Uttara Link)'), ('Airport uttara', 'Airport (Hazrat Shahjalal)'), ('Abdullahpur, Uttara', 'Abdullahpur'), ('Diabari', 'Diabari'), ('Kamarpara', 'Kamarpara'), ('Khilkhet', 'Khilkhet (East of Airport)'), ('Tongi', 'Tongi'), ('Shyamoli', 'Shyamoli'), ('Agargaon', 'Agargaon'), ('Kafrul', 'Kafrul (West Agargaon)'), ('Kazipara', 'Kazipara (Near Mirpur 10)'), ('Shewrapara', 'Shewrapara (On Mirpur Road)'), ('Taltola', 'Taltola (Mirpur-Mohammadpur link)'), ('Pallabi', 'Pallabi'), ('Alubdi', 'Alubdi (Pallabi outskirts)'), ('Monipur', 'Monipur (School & Housing Area)'), ('Mirpur DOHS', 'Mirpur DOHS'), ('Mirpur 1', 'Mirpur Section 1'), ('Mirpur 2', 'Mirpur Section 2'), ('Mirpur 6', 'Mirpur Section 6'), ('Mirpur 10', 'Mirpur Section 10'), ('Mirpur 11', 'Mirpur Section 11'), ('Mirpur 12', 'Mirpur Section 12'), ('Mirpur 14', 'Mirpur 14 (Kalshi)'), ('Mohammadpur', 'Mohammadpur'), ('Dhanmondi', 'Dhanmondi'), ('Farmgate', 'Farmgate')], max_length=100),
        ),
    ]
