# Generated by Django 5.2 on 2025-07-13 11:19

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate_finder', '0006_alter_roompost_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roompost',
            name='department',
            field=models.CharField(choices=[('Any', 'Any'), ('CSE', 'CSE'), ('ICT', 'ICT'), ('ES', 'Environmental Science'), ('ENG', 'English'), ('ECO', 'Economics'), ('IR', 'International Relations'), ('LAW', 'Law'), ('PA', 'Public Administration'), ('SOC', 'Sociology'), ('DS', 'Development Studies'), ('MCJ', 'Mass Communication & Journalism'), ('DMR', 'Disaster Management & Resilience'), ('PCHR', 'Peace, Conflict and Human Rights'), ('GEN', 'Business Administration - General'), ('AIS', 'Accounting & Information Systems'), ('MGT', 'Management Studies'), ('MKT', 'Marketing'), ('FNB', 'Finance & Banking'), ('BA/BSS', 'BA/BSS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='roompost',
            name='move_in_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='roompost',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+880100000000', max_length=128, region=None),
        ),
    ]
