# Generated by Django 5.2 on 2025-07-13 11:24

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='nextDoorPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('looking_tutions', 'Looking for Tuitions'), ('looking_tutor', 'Looking for Tutors')], max_length=16)),
                ('subjects', models.CharField(max_length=255)),
                ('budget', models.IntegerField()),
                ('medium', models.CharField(choices=[('bangla', 'Bangla Version'), ('english', 'English Version'), ('english_mid', 'English Medium'), ('any', 'Any')], max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], max_length=10)),
                ('location', models.CharField(choices=[('Uttara East', 'Uttara East'), ('Uttara General Hospital', 'Uttara West'), ('Uttara Center, Tafalia Main Road, Uludaha, Baunia, Dhaka, Dhaka Metropolitan,1231', 'Uttara Center'), ('House Building', 'House Building (Uttara Hub)'), ('Azampur', 'Azampur (Uttara Link)'), ('Airport uttara', 'Airport (Hazrat Shahjalal)'), ('Abdullahpur, Uttara', 'Abdullahpur'), ('Diabari', 'Diabari'), ('Kamarpara', 'Kamarpara'), ('Khilkhet', 'Khilkhet (East of Airport)'), ('Tongi', 'Tongi'), ('Shyamoli', 'Shyamoli'), ('Agargaon', 'Agargaon'), ('Kafrul', 'Kafrul (West Agargaon)'), ('Kazipara', 'Kazipara (Near Mirpur 10)'), ('Shewrapara', 'Shewrapara (On Mirpur Road)'), ('Taltola', 'Taltola (Mirpur-Mohammadpur link)'), ('Pallabi', 'Pallabi'), ('Alubdi', 'Alubdi (Pallabi outskirts)'), ('Monipur', 'Monipur (School & Housing Area)'), ('Mirpur DOHS', 'Mirpur DOHS'), ('Mirpur 1', 'Mirpur Section 1'), ('Mirpur 2', 'Mirpur Section 2'), ('Mirpur 6', 'Mirpur Section 6'), ('Mirpur 10', 'Mirpur Section 10'), ('Mirpur 11', 'Mirpur Section 11'), ('Mirpur 12', 'Mirpur Section 12'), ('Mirpur 14', 'Mirpur 14 (Kalshi)'), ('Adabar', 'Adabar'), ('Badda', 'Badda'), ('Bangsal', 'Bangsal'), ('Bashundhara', 'Bashundhara'), ('Cantonment', 'Cantonment'), ('Chawkbazar', 'Chawkbazar'), ('Dakshinkhan', 'Dakshinkhan'), ('Dhanmondi', 'Dhanmondi'), ('Gandaria', 'Gandaria'), ('Gulshan', 'Gulshan'), ('Hazaribagh', 'Hazaribagh'), ('Jatrabari', 'Jatrabari'), ('Kalabagan', 'Kalabagan'), ('Kamrangirchar', 'Kamrangirchar'), ('Khilgaon', 'Khilgaon'), ('Khilkhet', 'Khilkhet'), ('Kodomtoli', 'Kodomtoli'), ('Kotwali', 'Kotwali'), ('Lalbagh', 'Lalbagh'), ('Mirpur', 'Mirpur'), ('Mohammadpur', 'Mohammadpur'), ('Motijheel', 'Motijheel'), ('Mugda', 'Mugda'), ('New Market', 'New Market'), ('Paltan', 'Paltan'), ('Ramna', 'Ramna'), ('Rampura', 'Rampura'), ('Rupnagar', 'Rupnagar'), ('Sabujbagh', 'Sabujbagh'), ('Shah Ali', 'Shah Ali'), ('Shahbagh', 'Shahbagh'), ('Shahjahanpur', 'Shahjahanpur'), ('Shyampur', 'Shyampur'), ('Sutrapur', 'Sutrapur'), ('Tejgaon', 'Tejgaon'), ('Tejgaon Industrial Area', 'Tejgaon Industrial Area'), ('Turag', 'Turag'), ('Vatara', 'Vatara')], max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('student_class', models.CharField(choices=[('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('SSC', 'SSC'), ('HSC', 'HSC'), ('Admission', 'Admission'), ('ANY', 'ANY')], max_length=10)),
                ('details', models.TextField(blank=True, help_text='Write any extra details', null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
