# Generated by Django 5.2 on 2025-06-14 15:52

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('tech', 'Tech'), ('business', 'Business'), ('cp', 'Competitive programming'), ('debate', 'Debate'), ('hackathon', 'Hackathon'), ('ctf', 'Capture The Flag'), ('arts', 'Arts & Culture'), ('career', 'Career / Skill'), ('social', 'Social Work'), ('research', 'Research / Academic'), ('sports', 'Sports'), ('general', 'General'), ('others', 'Others')], max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='eventPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('seminar', 'Seminar'), ('workshop', 'Workshop'), ('cultural', 'Cultural Program'), ('sports', 'Sports Event'), ('contest', 'Contest')], max_length=16)),
                ('event_title', models.CharField(blank=True, max_length=100, null=True)),
                ('theme', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
                ('deadline', models.DateTimeField(help_text='Last date/time to register')),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('payment', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], max_length=10)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='event_posters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(related_name='event_posts', to='event_manager.eventcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='event_manager.eventpost')),
            ],
        ),
        migrations.CreateModel(
            name='UserBusySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busy_slots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserEventSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance_score', models.PositiveIntegerField(default=1)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.eventpost')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.ManyToManyField(through='event_manager.UserEventSelection', to='event_manager.eventpost')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usereventselection',
            name='user_routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.userroutine'),
        ),
        migrations.AlterUniqueTogether(
            name='usereventselection',
            unique_together={('user_routine', 'event')},
        ),
    ]
