# Generated by Django 5.2 on 2025-06-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbusyslot',
            name='task_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
