# Generated by Django 5.2 on 2025-06-19 21:22

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0002_userbusyslot_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='eventsegment',
            name='event',
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.DeleteModel(
            name='EventCategory',
        ),
        migrations.AddField(
            model_name='eventpost',
            name='category',
            field=models.CharField(choices=[('tech', 'Tech'), ('business', 'Business'), ('cp', 'Competitive programming'), ('debate', 'Debate'), ('hackathon', 'Hackathon'), ('ctf', 'Capture The Flag'), ('arts', 'Arts & Culture'), ('career', 'Career / Skill'), ('social', 'Social Work'), ('research', 'Research / Academic'), ('sports', 'Sports'), ('general', 'General'), ('others', 'Others'), ('', '')], default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='EventSegment',
        ),
    ]
