# Generated by Django 5.2 on 2025-06-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0003_remove_eventpost_category_remove_eventsegment_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpost',
            name='has_conflict',
            field=models.BooleanField(default=False),
        ),
    ]
