# Generated by Django 5.2 on 2025-06-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0004_eventpost_has_conflict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpost',
            name='has_conflict',
        ),
        migrations.AddField(
            model_name='usereventselection',
            name='has_conflict',
            field=models.BooleanField(default=False),
        ),
    ]
