# Generated by Django 5.2 on 2025-06-23 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0005_remove_eventpost_has_conflict_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose', models.CharField(choices=[('1', '1 Event'), ('2', '2 Events'), ('3', '3 Events'), ('4', '4 Events'), ('5', '5 Events')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommendation Preference',
                'verbose_name_plural': 'Recommendation Preferences',
                'ordering': ['-created_at'],
            },
        ),
    ]
