# Generated by Django 5.2 on 2025-06-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0006_recom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recom',
            name='choose',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4 '), ('5', '5')], max_length=10),
        ),
    ]
